executor: slurm

slurm:
  job-name: "{rule}.{wildcards}"
  account: schmidlab
  partition: schmidlab
  nodes: 1
  cpus-per-task: "{threads}"
  mem: "{resources.mem_gb}G"
  output: "log/jobs/{rule}_{wildcards}_%j.out"
  error: "log/jobs/{rule}_{wildcards}_%j.err"

jobs: 40
retries: 2

default-resources:
  threads: 1
  mem_gb: 4
  time: "24:00:00"
