# Path to the samples table (CSV file)
samples: "data/samples.csv"

# Output directories
output_dirs:
  raw_data: "/work/als185/rna_seq_full_data"
  trimmed: "/work/als185/rnaseq_tmp_files/results/trimmed_fq"
  mapped: "/work/als185/rnaseq_tmp_files/results/mapped_reads"
  sorted: "/work/als185/rnaseq_tmp_files/results/mapped_sorted_reads"
  qc: "results/qc"
  htseq: "results/htseq_counts"

# Reference genome and annotation files
reference:
  genome_dir: "resources/genomes/h_vol/indexes"
  gff: "resources/genomes/h_vol/genomic.gff"

# Conda environments
envs:
  fastp: "workflow/envs/fastp.yaml"
  qc: "workflow/envs/qc.yaml"
  rna_seq_processing: "workflow/envs/rna_seq_processing.yaml"